### ISSUE TITLE
Error while running the code on Colab

### ISSUE THREAD

**Issue by IssaIssa1** [arkadaw9/PGNN#2]
Hello I am trying to run your code on colab. 
But I am getting the following error I can't see how I may fix it. Any ideas?
```
Traceback (most recent call last):
  File "PGNN.py", line 148, in <module>
    PGNN_train_test(optimizer_name, optimizer_val, drop_frac, use_YPhy, iteration, n_layers, n_nodes, tr_size, lamda, lake_name)
  File "PGNN.py", line 110, in PGNN_train_test
    spio.savemat(results_name, {'train_loss_1':history.history['loss_1'], 'val_loss_1':history.history['val_loss_1'], 'train_rmse':history.history['root_mean_squared_error'], 'val_rmse':history.history['val_root_mean_squared_error'], 'test_rmse':test_score[2]})
KeyError: 'loss_1'
```

**Comment by costarichard** [comment]
Hi, getting the same error. How to fix it?
